### ISSUE TITLE
`lb` freeze at "Enter name of the directory to contain the project" question

### ISSUE THREAD

**Issue by cdokolas** [strongloop/loopback-cli#36]
### Bug or feature request

- [x] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)
I run `lb` but I only get as far as the "Enter name of the directory to contain the project" question, where I can't type anything in or exit via `Ctrl-C`.

Same behavior with administrative command prompt. Powershell or classic prompt doesn't affect result.

Tried re-installing `loopback-cli` (npm uninstall/install). Same.

### Expected result
I should be able to enter the directory name for my new project and continue.

### Actual result (if bug)
Prompt stuck, not accepting input. Nothing to do but shut-down the terminal window.

### Additional information (Node.js version, LoopBack version, etc)
node.js: *v8.1.0*
npm.js: *5.0.3*
loopback-cli (via `lb -v`): *2.5.1 (generator-loopback@3.7.0 loopback-workspace@3.40.1)*
Windows 10 Pro 64-bit (with Creators Update; fully updated/patched as of posting)

## Acceptance Criteria
- [ ] verify if the problem still exists 
- [ ] if problem still exists, put debug statements to identify the bottleneck
- [ ] see if we can fix the bottleneck

**Comment by Omar-allahham** [comment]
here the same!

**Comment by juanpedrob9** [comment]
I got basically the same problem here, I can enter the app name but it freeze at second step when you get to choose loopback version. Same result when installed with either npm or yarn. Ctrl-C don't work got to kill -9 pid for it to exit.

loopback-cli: 2.5.1 (generator-loopback@3.7.0 loopback-workspace@3.40.1) 
node: 8.1.0
npm: 5.0.3 / yarn 0.24.6
Fedora 25: 4.11.3-202.fc25.x86_64

**Comment by raymondfeng** [comment]
I can reproduce the issue with node 8.1.0. It works with node 8.0.0.

**Comment by cdokolas** [comment]
Tried strongloop/generator-loopback (yeoman generator) and found the same behavior. Anyone able to further look into it? (I lack the know-how)

**Comment by raymondfeng** [comment]
I see the same problem with https://github.com/yeoman/generator-node. I'll open an issue for yeoman.

**Comment by raymondfeng** [comment]
It's a bug in Node 8.1. See https://github.com/nodejs/node/issues/13557.

**Comment by NadhiyaMajeed** [comment]
Hi

Am facing lb freeze after giving the application name.
node version - v10.6.0
npm version=6.1.0
loopback- 4.2.0
OS- windows10

can anybody help me here since am new to loopback.

**Comment by gezbo** [comment]
I'm also experiencing lb freeze after giving the application name.

node version - v10.7.0
npm version=6.1.0
loopback- 4.2.0
OS- windows10

anyone help please?

**Comment by bennoll** [comment]
I'm also encountering `lb` freeze after entering the application name.

Program  | Version
------ | ----------
node | v10.10.0
npm  | 6.4.1
loopback | 4.2.1
OS | Windows 8

**Comment by NadhiyaMajeed** [comment]
Hi

2 months back i was trying this. i dont remember which one i was installing LTS or current.
if you have tried installing current and getting error go for LTS, then this error will not be getting.

Thanks
Nadhiya.P.M

**Comment by andenis** [comment]
The problem is the same in the last node version for Windows (x64) Nodejs: 10.12.0.
For NodeJs version 8.12.0 works fine.

**Comment by Patafix** [comment]
Same problème here : 

lb -v 4.2.1 (generator-loopback@5.9.4 loopback-workspace@4.5.0)
node -v  v10.7.0

**Comment by median-man** [comment]
Same issue here. 

lb -v 4.2.1 (generator-loopback@5.9.4 loopback-workspace@4.5.0)
node -v v10.13.0

**Comment by bajtos** [comment]
FWIW, we have been observing freezups on our CI servers since Node.js 10.2.0 was released, but weren't able to pinpoint the problem. You can read the discussion in https://github.com/nodejs/node/issues/21210 to learn about the ways I tried to debug this problem. It would be awesome if somebody on Windows can check whether the problem can be reproduced using the latest Windows and Node.js versions.

**Comment by Flash619** [comment]
I can confirm this same behavior.

Node: 10.13.0
NPM: 6.4.1
Loopback: 4.2.1
Generator Loopback: 5.9.4
Loopback Workspace: 4.5.0
Windows 10: (v1803)

**Comment by tsnork** [comment]
FWIW, debugging loopback-cli crashes repeatedly at marked line in screenshot. Seems to be the point the application stops responding:

https://i.imgur.com/T0Zlb0K.png

**Comment by nabdelgadir** [comment]
Program  | Version
------ | ----------
node | 8.14.0/10.14.1
npm  | 6.4.1
loopback | 5.0.0
OS | Windows 10

Using the above versions, I'm not able to reproduce the error. It does lag when using the `lb app` command however, but it doesn't freeze: 

<img width="1280" alt="screen shot 2018-12-06 at 3 20 49 pm" src="https://user-images.githubusercontent.com/42985749/49609783-8c454680-f96a-11e8-8bb0-beb5674ba36f.png">

I was also able to create a datasource and model. Try updating to the latest versions and see if you're still running into the same errors.

**Comment by jannyHou** [comment]
Closing this issue since we couldn't  reproduce it. Feel free to reopen it if you still have the problem (make sure you update node/npm/dependencies) as comment https://github.com/strongloop/loopback-cli/issues/36#issuecomment-445025008 :)

**Comment by smartmouse** [comment]
can reproduce on windows 10.
node 10.15.1
npm 6.4.1

**Comment by dhmlau** [comment]
@nabdelgadir, since you cannot reproduce it using `loopback-cli@5.x` but it seems like others are referring to 4.x, I'd like to propose the following actions:
1. Confirm whether this issue only happens in `loopback-cli@4.x` with the same node.js version and windows machine.
2. If that's the case, we might need to investigate what's changed in 5.x that fixes the problem.  (I don't recall we're fixing any hanging/latency issue for 5.x but @jannyHou probably knows the best)

**Comment by smartmouse** [comment]
This issue seems to be windows specific, at least it works for me on mac and linux for node 10.15.1

**Comment by nabdelgadir** [comment]
<img width="1289" alt="screen shot 2019-02-04 at 8 57 34 am" src="https://user-images.githubusercontent.com/42985749/52212639-030f9a80-285b-11e9-8920-fa395141b8e0.png">

Using node `10.15.1`, I tried `loopback-cli@4.2.1`, `4.2.0`, `4.0.0`, and even `3.1.0` but all of them seem to have the same problem. The only one that works is `loopback-cli@5.0.0`. I suspect it was fixed by something done in this [one PR](https://github.com/strongloop/loopback-cli/pull/71) by @jannyHou which occurred between `4.2.1` and `5.0.0`.

**Comment by dhmlau** [comment]
Thanks @nabdelgadir. For those who have reported the issue here, it seems like this lagging/hanging problem no longer exist in `loopback-cli@5.0.0`.  Could you please try to see if it works for you?

@smartmouse, it might be a good time to upgrade to use the latest version for API Connect v2018.x.  Thanks.

**Comment by dhmlau** [comment]
Closing as resolved as this problem no longer exists in `loopback-cli@5.0.0`.

**Comment by hashirQburst** [comment]
The problem still exist on loopback-cli@5.0.0 mac
5.0.0 (generator-loopback@6.0.4 loopback-workspace@5.0.0)
node v10.2.0
npm 6.1.0

freezes on second question

**Comment by straeger** [comment]
same problem on my mac
5.0.2 (generator-loopback@6.0.4 loopback-workspace@5.0.0)
node 11.9.0
npm 6.5.0

**Comment by KietChan** [comment]
Sorry, but I'm still facing this problem on the new version.
- OS: Ubuntu 18.04.2
- Node: v12.4.0
- npm: 6.9.0
- 5.0.0 (generator-loopback@6.0.4 loopback-workspace@5.0.0)

**Comment by nabdelgadir** [comment]
I think this PR https://github.com/strongloop/loopback-cli/pull/89 might resolve the issue.

**Comment by dhmlau** [comment]
@hashirQburst @straeger @KietChan, there's a new issue in `inquirer` (see https://github.com/SBoudrias/Inquirer.js/issues/811) that causes the hanging.  PR #89 that @nabdelgadir mentioned will make loopback-cli to use a lower version of `inquirer`.
